### ISSUE TITLE
on change page not trigger

### ISSUE THREAD

**Issue by vladanzivanovic** [PeachScript/vue-infinite-loading#101] opened 2017-10-18 12:30 UTC
### Version
2.2.1

### Vue.js version
2.4.4

### What is expected?
It expected to trigger function to load new data.

### What is actually happening?

page has two components that use this plugin when I change page and get back to this, only first infinite is triggered. If I reload the page then both were triggered.

Components are attached here

[Archive.zip](https://github.com/PeachScript/vue-infinite-loading/files/1394583/Archive.zip)

**Comment by PeachScript** [comment] 2017-10-19 02:22
Are these InfiniteLoading component be destroyed?

And if you can, please reproduce it through a MVP(Minimum Viable Program) on some website like [JSFiddle](https://jsfiddle.net), thank you.

**Comment by raphaelsoul** [comment] 2017-11-08 14:19
similiar problem, when refreshing page, it will trigger an `infinite` event, when switch from another router, this event was not triggerd.

**Comment by PeachScript** [comment] 2017-11-15 08:39
@raphaelsoul could you reproduce it with live demo? I cannot locate the reason base on the current informations.

**Comment by yenchieh** [comment] 2018-01-09 17:04
@raphaelsoul 
Not sure if I fully understand your issue.
If you are using vue-router, the solution to fix your issue is to add "key" property to the router-view otherwise the components will not be cached separately, so once you call `$state.complete`, all of pages stop trigger `@infinite`.
Example:
`
<router-view :key="pageName"></router-view>
`

**Comment by PeachScript** [comment] 2018-01-18 13:08
Thank you @yenchieh , but this issue has no updates, so I will close it.

**Closed by PeachScript** 2018-01-18 13:08 UTC
