### ISSUE TITLE
_this.$refs.infiniteLoading.$emit is not a function

### ISSUE THREAD

**Issue by tengqingya** [PeachScript/vue-infinite-loading#57] opened 2017-06-21 08:53 UTC
code：
`loadMore: function () {
        console.log("loadMore")
            getChartDetail({id: this.charts[this.activeIndex]['id'],offset:this.chartsArray[this.activeIndex].length}).then(e=>{
              this.chartsArray[this.activeIndex].push(...e.books)
          this.$refs.infiniteLoading&&this.$refs.infiniteLoading.$emit('$InfiniteLoading:loaded');
        }).catch(e => {
            console.log(e)
        })
      }`
first time it will work，but when i continue to scroll ,next time will produce error ‘_this.$refs.infiniteLoading.$emit is not a function’

**Comment by emkman** [comment] 2017-06-21 22:24
Same issue
`Cannot read property '$emit' of undefined`
Seems the ref doesn't register properly for some reason.

**Comment by PeachScript** [comment] 2017-06-22 01:43
Could you reproduce this problem on [JSFiddle](https://jsfiddle.net)?

**Comment by feinimoshu753** [comment] 2017-06-29 01:56
@emkman maybe is this reason? . When ref is used together with v-for, the ref you get will be an array containing the child components mirroring the data source.

**Comment by jkiimm** [comment] 2017-07-24 15:50
@PeachScript I have the same issue. it seems to be happened when a view is changed while some resource is loading.

```js
const things = await fetchSomething() // the view(page) is changed while waiting for `fetchSomething`
this.$refs.loader.$emit('$InfiniteLoading:loaded')
```

I guess https://github.com/vuejs/vue-router/issues/1181 is related with it.

**Comment by PeachScript** [comment] 2017-07-25 02:08
Oh...sounds like that, thanks! I think If we plan to use `await`, we also should to process every possibility, through the result of `await` to decide whether execute the `$emit` statement, how do you think about it?

**Comment by zzmm1** [comment] 2017-07-26 08:20
同样的问题，请问怎么解决？
“Uncaught (in promise) TypeError: Cannot read property '$emit' of undefined”

**Comment by PeachScript** [comment] 2017-07-26 10:05
@zzmm1 暂时还没定位到真正的原因，只是有一些推测，有待验证。不知道你是否可以在 [JSFiddle](https://jsfiddle.net) 上重现你遇到的问题?

**Comment by zzmm1** [comment] 2017-07-27 07:15
未加载完成就停止，就会出现该错误。

**Comment by zzmm1** [comment] 2017-07-31 01:44
持续关注中.....

**Comment by PeachScript** [comment] 2017-07-31 10:01
@zzmm1 ，感谢，但我还没找到比较好的解决办法，也许应该换一种使用方式

**Comment by xuyukuan** [comment] 2017-08-20 01:10
+1

**Comment by PeachScript** [comment] 2017-08-23 15:22
Hi everyone @tengqingya @emkman @feinimoshu753 @jkiimm @zzmm1 @xuyukuan , I think this problem cannot be fixed if this component still use `$refs` to send event, because it cannot ensure the ref element always be accessible. For example if this component already was destroyed after the async request complete in the `on-infinite` function, but the callback function still try to emit event through the `$refs.infiniteLoading`, this error will be thrown.

So I plan to change the way to send the `loaded` and `complete` event, it may looks like this:

```js
...
infiniteHandler(state) {
  ajax('https://www.google.com', (data) => {
    if (data.length) {
      state.loaded();
    } else {
      state.complete();
    }
  });
}
...
```

What do you think? And how about the variable name `state`?

Best regards.

**Comment by PeachScript** [comment] 2017-09-15 14:00
Hi everyone, [v2.2.0](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.0) has been released, include this change, you can try it now, please feedback to here if you find any question, thanks :D

**Comment by FEcorlin** [comment] 2017-09-16 06:49
oh!  I have the same issue with v2.2.0(vue v2.4.3).  
```
this.$nextTick(() => {
        this.$refs.scrollWrapper.$emit('$InfiniteLoading:reset');
 });
```
`Error in nextTick: "TypeError: _this2.$refs.scrollWrapper.$emit is not a function`。
thanks for help。

**Comment by PeachScript** [comment] 2017-09-17 07:32
@FEcorlin did you `$emit` this event after the component be destroyed?

**Comment by PeachScript** [comment] 2017-09-25 10:52
No updates, I will close this issue, you can reopen it if you need in the future.

**Closed by PeachScript** 2017-09-25 10:52 UTC
Labels: enhancement

**Comment by bruddah** [comment] 2017-09-27 12:59
Hi, I have a question - I need to stop loader depending on some condition in one of the methods, that has nothing to do with `infiniteHandler`. Currently I do it by using $ref:

```
if ( this.$refs.infiniteLoading)
    this.$refs.infiniteLoading.$emit('$InfiniteLoading:loaded');
```
so I'm getting [Vue-infinite-loading warn], which is tripping me up and it seems like there's no other way -
 is there?

**Comment by PeachScript** [comment] 2017-09-28 02:22
@bruddah you can use the `this.$refs.infiniteLoading.stateChanger.loaded()` method to do that.

**Comment by aoyoo111** [comment] 2022-09-24 16:15
> @Bruddah you can use the `this.$refs.infiniteLoading.stateChanger.loaded()` method to do that.

nice

**Comment by ErikaWorm** [comment] 2024-05-15 13:23
> @Bruddah you can use the `this.$refs.infiniteLoading.stateChanger.loaded()` method to do that.

I get an error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'loaded')`
Does anyone have the same issue?
