### ISSUE TITLE
Infinite scroll triggering countinously

### ISSUE THREAD

**Issue by gijo-varghese** [PeachScript/vue-infinite-loading#110] opened 2017-11-18 15:04 UTC
On reaching the bottom, the event triggers multiple time so that the full list is loaded. Is there any particular reason for this? Looks like the plugin didn't get those new elements are added. It keeps on addng...

**Comment by oixan** [comment] 2017-11-19 10:13
Same happend here. Installed right now.
"vue": "^2.5.5",
"vue-infinite-loading": "^2.2.1",

**Comment by PeachScript** [comment] 2017-11-19 14:21
@gijo-varghese @oixan could you reproduce it through a live demo?

@gijo-varghese this plugin will not detecting new elements, it judge through the `scrollTop` of the scroll wrapper element.

**Comment by gijo-varghese** [comment] 2017-11-19 14:36
@PeachScript the plugin was working fine till a few days back. So I think it's a bug a in the latest version. I'll create a repo to reproduce the same soon

**Comment by PeachScript** [comment] 2017-11-19 15:00
@gijo-varghese thanks! But the latest version was released a month ago, is that the real reason?

**Comment by gijo-varghese** [comment] 2017-11-20 04:45
@PeachScript let me check it in detail. Have to make sure that it isn't a bug from my side.

**Comment by oixan** [comment] 2017-11-20 22:12
This is definitely a bug. 
I make a basic live example where you can just scroll and see that the method infinityScroll is in loop.
https://jsfiddle.net/a7x5zdr7/

**Comment by gijo-varghese** [comment] 2017-11-21 03:00
@oixan well done! @PeachScript I think that makes sense?

**Comment by PeachScript** [comment] 2017-11-21 06:28
@oixan @gijo-varghese thanks! It looks like an expected result, because this plugin will triggering continuously if the distance still expected after called the `loaded` method, and if I push five elements each time, it will not triggering continuously, this is a live demo base on @oixan : https://jsfiddle.net/a7x5zdr7/2/

You can also set the `distance` property to solve this, default value is `100`:
```html
<infinite-loading :distance="10"></infinite-loading>
```

**Comment by gijo-varghese** [comment] 2017-11-21 06:31
So `distance` is the height added after adding the new data? So the by default if new data added's height is less than 100px it will trigger again right? What if I make the distance as 0?

What is the exact definition of this `distance`?

**Comment by PeachScript** [comment] 2017-11-21 06:37
Doc is [here](https://peachscript.github.io/vue-infinite-loading/#!/properties), hope it help you.

**Comment by gijo-varghese** [comment] 2017-11-21 06:39
@PeachScript Thanks. Let me try to fix it in my project

**Comment by PeachScript** [comment] 2017-11-21 07:06
@gijo-varghese you're welcome :)

**Comment by oixan** [comment] 2017-11-21 14:02
After few test i think the plugin is working fine. 
Just to clarify, if after the handler call the height scroll is under the threshold distance the handler will be invoked untill the height scroll is before  the threshold.
this can generate a feeling of loop. 

Anyway in my case the plugin is still not working. At this point, I think, the problem is related to masonry plugin. I think these 2 plugin cant work togheter. @PeachScript any info about this?

```  javascript 
<div class="masonry-grid" >

       <div class="masonry-grid-sizer"></div>

       <div class="masonry-grid-item" v-for="item in items">
               ...
       </div>

       <infinite-loading @infinite="infiniteHandler" :distance="100"></infinite-loading>

</div>```

**Comment by PeachScript** [comment] 2017-11-22 02:50
@oixan could you provide a live demo with masonry?

**Comment by mlg-mbojcic** [comment] 2017-11-24 16:25
For me it starts triggering without any scrolling. It started happening after I updated to 2.2.2 version. If I go back to 2.2.1 it works normally.

**Comment by damienbeaufils** [comment] 2017-12-08 10:25
I think this issue is related to the same regression mentioned in https://github.com/PeachScript/vue-infinite-loading/issues/111#issuecomment-350226525

**Comment by PeachScript** [comment] 2017-12-10 08:26
@damienbeaufils I think so, perhaps also include #114

**Comment by PeachScript** [comment] 2017-12-11 13:44
@gijo-varghese @oixan @mlg-mbojcic hello everyone, I have been released a new version [v2.2.3](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.3) to try to fix this problem, you can try it now, if it still not working, please tell me, thanks!

**Comment by gijo-varghese** [comment] 2017-12-11 13:57
Thanks. Will try it

**Comment by PeachScript** [comment] 2017-12-14 14:04
@gijo-varghese you're welcome :)

**Closed by PeachScript** 2017-12-14 14:04 UTC

**Comment by gijo-varghese** [comment] 2018-01-04 11:37
@PeachScript it's still not working. Same issue

**Comment by gijo-varghese** [comment] 2018-01-05 04:56
@PeachScript So I figured out the issue. There is no problem when it's adding new elements to bottom (position=bottom). But while adding new elements to top (position=top) the browser pushes the entire list down so that even after adding new elements view will be on top. This article helped be to solve the issue: http://kirbysayshi.com/2013/08/19/maintaining-scroll-position-knockoutjs-list.html

What I did is:
```
let current_height = document.getElementById("list-container").scrollHeight;
...
// add new elements to top
...
let new_height = document.getElementById("list-container").scrollHeight;
document.getElementById("list-container").scrollTop = new_height - current_height;
```

**Comment by gijo-varghese** [comment] 2018-01-05 04:57
it would be great if you can add this script when the `position="top"`

**Comment by PeachScript** [comment] 2018-01-05 08:41
@gijo-varghese thanks! I will seriously consider.
